name: banner_carousel
description: A Widget horizontal scrollable list with indicator and animations.
version: 1.2.1
homepage: https://github.com/MaiaraM/banner_carousel

environment:
  sdk: '>=3.9.0'
  flutter: ">=3.35.3"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
